#web:
#  build: .
#  ports:
#   - "8080:8080"
#
#
nginx:
    build: nginx/
    links:
        - node1:node1
        - node2:node2
    ports:
        - "80:80"
node1:
    build: .
    ports:
        - "8080"
node2:
    build: .
    ports:
        - "8080"