version: '2'

services:
    nginx:
        build: nginx/
        links:
            - web:web
    #        - node2:node2
        ports:
            - "80:80"
        networks:
            - web-net
        restart: always


    web:
        build: web/.
#        links:
#            - hello:hello
#            - world:world
        ports:
            - "8080"
        networks:
            - web-net
            - hello-net
            - world-net
        restart: always
#        hostname: web-node
#        environment:
#            - DOCKER_HOST
#            - DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock"
#            - DOCKER_TLS_VERIFY=1
#            - DOCKER_URL=unix:///var/run/docker.sock
#            - DOCKER_CERT_PATH=/etc/ssl/certs/


    hello:
        build: hello/.
        ports:
            - "8080"
        networks:
            - hello-net
        restart: always
#        environment:
#            - DOCKER_HOST
#            - DOCKER_CERT_PATH
        hostname: "hello"


    world:
        build: world/.
        ports:
            - "8080"
        networks:
            - world-net
        restart: always
#        environment:
#            - DOCKER_HOST
#            - DOCKER_CERT_PATH
        hostname: "world"

#networks:
#    my-net:
#        driver: overlay

#networks:
#  default:
#    external:
#        name: web-net
#        name: hello-net
#        name: world-net

networks:
  web-net:
    external: true
  hello-net:
    external: true
  world-net:
    external: true